{% set version = "0.3.0" %}

package:
  name: cladebreaker
  version: {{ version }}
source:
  url: https://github.com/andriesfeder/cladebreaker/archive/refs/tags/v{{ version }}.tar.gz
  sha256: REPLACE_WITH_SHA256_OF_v0.3.0_TARBALL
build:
  noarch: generic
  number: 0
requirements:
  host:
    - python=3.10
  run:
    - python
    - biopython
    - nextflow
    - graphviz
test:
  commands:
    - "cladebreaker --version"

about:
  home: https://github.com/andriesfeder/cladebreaker
  license: MIT
  summary: Nextflow pipeline for phylogenetic analysis.
extra:
  container:
    extended-base: true
  copy_test_source_files: true
  final: true
